"""Dump the database using pg_dump if available, or export a simple SQL fallback.

This script attempts to invoke `pg_dump` from PATH. If it's not
available, it will connect using psycopg2 and export table schemas and
rows in a lightweight SQL format (best-effort).
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from urllib.parse import urlparse

import psycopg2


def run_pg_dump(out_path: str) -> bool:
    pg_dump = shutil.which("pg_dump")
    if not pg_dump:
        return False
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise EnvironmentError("DATABASE_URL not set")
    # Use the URL as the DSN for pg_dump
    cmd = [pg_dump, "--dbname", database_url, "-f", out_path]
    subprocess.check_call(cmd)
    return True


def fallback_export(out_path: str):
    # Connect and export simple CREATE TABLE + INSERTs for banks and reviews
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise EnvironmentError("DATABASE_URL not set")
    parsed = urlparse(database_url)
    conn = psycopg2.connect(host=parsed.hostname, port=parsed.port, dbname=parsed.path.lstrip('/'), user=parsed.username, password=parsed.password)
    cur = conn.cursor()
    # Export banks
    with open(out_path, 'w', encoding='utf8') as f:
        f.write('-- Dump generated by scripts/dump_db.py (fallback)\n')
        cur.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'banks'")
        # Schema export is non-comprehensive; we focus on data
        cur.execute("SELECT * FROM banks")
        rows = cur.fetchall()
        if rows:
            for row in rows:
                vals = ', '.join([f"'{str(x).replace("'","''")}'" if x is not None else 'NULL' for x in row])
                f.write(f"INSERT INTO banks VALUES ({vals});\n")
        cur.execute("SELECT * FROM reviews")
        rows = cur.fetchall()
        if rows:
            for row in rows:
                vals = ', '.join([f"'{str(x).replace("'","''")}'" if x is not None else 'NULL' for x in row])
                f.write(f"INSERT INTO reviews VALUES ({vals});\n")
    cur.close()
    conn.close()


def main():
    out = Path('customer_fintec_dump.sql')
    try:
        ok = run_pg_dump(str(out))
        if ok:
            print(f'pg_dump succeeded -> {out}')
            return
    except Exception as e:
        print('pg_dump failed:', e)

    print('Falling back to simple export...')
    fallback_export(str(out))
    print(f'Fallback export written to {out}')


if __name__ == '__main__':
    main()
